name: my-sop-sketch
version: '0.1.0.0'
category: Web
author: Kris Jenkins
maintainer: krisajenkins@gmail.com
copyright: 2017 Kris Jenkins
license: BSD3
github: krisajenkins/my-sop-sketch
extra-source-files:
- README.md
library:
  source-dirs: src
  dependencies:
  - base
  - aeson
  - time
  - text
  - tagged
  - generics-sop
tests:
  my-sop-sketch-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - my-sop-sketch
    - hspec
    - QuickCheck
